export const CREATE_MOVIE_REQUEST="CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS="CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL="CREATE_MOVIE_FAIL";
export const CREATE_MOVIE_RESET="CREATE_MOVIE_RESET";

export const ADD_CAST="ADD_CAST"
export const EDIT_CAST="EDIT_CAST"
export const DELETE_CAST="DELETE_CAST"
export const RESET_CAST="RESET_CAST"