
export const MOVIE_LIST_REQUEST="MOVIE_LIST_REQUEST"
export const MOVIE_LIST_SUCCESS="MOVIE_LIST_SUCCESS"
export const MOVIE_LIST_FAIL="MOVIE_LIST_FAIL"
export const MOVIE_LIST_RESET="MOVIE_LIST_RESET"

export const MOVIE_RANDOM_REQUEST="MOVIE_RANDOM_REQUEST"
export const MOVIE_RANDOM_SUCCESS="MOVIE_RANDOM_SUCCESS"
export const MOVIE_RANDOM_FAIL="MOVIE_RANDOM_FAIL"

export const MOVIE_DETAILS_REQUEST="MOVIE_DETAILS_REQUEST"
export const MOVIE_DETAILS_SUCCESS="MOVIE_DETAILS_SUCCESS"
export const MOVIE_DETAILS_FAIL="MOVIE_DETAILS_FAIL"
export const MOVIE_DETAILS_RESET="MOVIE_DETAILS_RESET"

export const MOVIE_TOP_RATED_REQUEST="MOVIE_TOP_RATED_REQUEST"
export const MOVIE_TOP_RATED_SUCCESS="MOVIE_TOP_RATED_SUCCESS"
export const MOVIE_TOP_RATED_FAIL="MOVIE_TOP_RATED_FAIL"







// **************Admin******************
export const CREATE_MOVIE_REQUEST="CREATE_MOVIE_REQUEST";
export const CREATE_MOVIE_SUCCESS="CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL="CREATE_MOVIE_FAIL";
export const CREATE_MOVIE_RESET="CREATE_MOVIE_RESET";

export const ADD_CAST="ADD_CAST"
export const EDIT_CAST="EDIT_CAST"
export const DELETE_CAST="DELETE_CAST"
export const RESET_CAST="RESET_CAST"
