export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"
export const USER_LOGIN_RESET="USER_LOGIN_RESET"
export const USER_LOGOUT="USER_LOGOUT"



export const USER_REGISTE_REQUEST="USER_REGISTE_REQUEST"
export const USER_REGISTE_SUCCESS="USER_REGISTE_SUCCESS"
export const USER_REGISTE_FAIL="USER_REGISTE_FAIL"
export const USER_REGISTE_RESET="USER_REGISTE_RESET"