export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL="USER_LOGIN_FAIL"
export const USER_LOGIN_RESET="USER_LOGIN_RESET"
export const USER_LOGOUT="USER_LOGOUT"



export const USER_REGISTE_REQUEST="USER_REGISTE_REQUEST"
export const USER_REGISTE_SUCCESS="USER_REGISTE_SUCCESS"
export const USER_REGISTE_FAIL="USER_REGISTE_FAIL"
export const USER_REGISTE_RESET="USER_REGISTE_RESET"


export const USER_UPDAT_PROFILE_REQUEST="USER_UPDAT_PROFILE_REQUEST";
export const USER_UPDAT_PROFILE_SUCCESS="USER_UPDAT_PROFILE_SUCCESS";
export const USER_UPDAT_PROFILE_FAIL="USER_UPDAT_PROFILE_FAIL";
export const USER_UPDAT_PROFILE_RESET="USER_UPDAT_PROFILE_RESET";

export const USER_DELETE_PROFILE_REQUEST="USER_DELETE_PROFILE_REQUEST";
export const USER_DELETE_PROFILE_SUCCESS="USER_DELETE_PROFILE_SUCCESS";
export const USER_DELETE_PROFILE_FAIL="USER_DELETE_PROFILE_FAIL";
export const USER_DELETE_PROFILE_RESET="USER_DELETE_PROFILE_RESET";


export const USER_CHANGE_PASSWORD_REQUEST ="USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS ="USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL ="USER_CHANGE_PASSWORD_FAIL";
export const USER_CHANGE_PASSWORD_RESET ="USER_CHANGE_PASSWORD_RESET";